# -*- coding: utf-8 -*-
"""AI Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rbSiwr2PvT5XcSw_uqxkv-80fvshMjP

**GlucoSense – AI-Based Diabetes Prediction System**

Project Description:
GlucoSense is an AI-based system designed to predict the risk of diabetes using machine learning techniques. The system analyzes medical data and provides an early warning to help prevent complications.

Objectives:
- Predict the likelihood of diabetes using patient data  
- Enable early detection of high-risk individuals  
- Provide an intelligent alert system  
- Compare machine learning models for best performance

Dataset:
The dataset used in this project is the Pima Indians Diabetes Dataset from Kaggle.

Features:
- Pregnancies  
- Glucose  
- Blood Pressure  
- Skin Thickness  
- Insulin  
- BMI  
- Diabetes Pedigree Function  
- Age

Target:
- Outcome (0 = No Diabetes, 1 = Diabetes)

Technologies Used
- Python  
- Scikit-learn  
- Pandas & NumPy  
- Machine Learning Models:
  - Logistic Regression  
  - Random Forest

Machine Learning Models

### 1. Logistic Regression
A simple and effective algorithm used for binary classification problems.

### 2. Random Forest
An ensemble learning method that improves accuracy by combining multiple decision trees.

Methodology

### 1. Data Collection
- Dataset loaded from CSV file

### 2. Data Preprocessing
- Handling missing values  
- Replacing invalid zeros  
- Feature scaling using StandardScaler  

### 3. Data Splitting
- 80% Training  
- 20% Testing  

### 4. Model Training
- Logistic Regression  
- Random Forest  

### 5. Model Evaluation
- Accuracy Score  
- Confusion Matrix  
- Classification Report  

### 6. Prediction System
- Input new patient data  
- Output risk probability  
- Generate alert if risk is high

GlucoSense Alert System
- High Risk → Probability > 70%  
- Medium Risk → 40% – 70%  
- Low Risk → < 40%  

##  Results
- Random Forest achieved higher accuracy compared to Logistic Regression  
- The system successfully predicts diabetes risk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data = pd.read_csv('diabetes.csv')
print("Dataset Loaded Successfully")
print(data.head())

plt.figure(figsize=(6,5))
data['Outcome'].value_counts().plot.pie(labels=['No Diabetes', 'Diabetes'], autopct='%1.1f%%', colors=['#3498db', '#e74c3c'])
plt.title('Diabetes Dataset Distribution')
plt.ylabel('')
plt.show()

data.hist(figsize=(12, 10), color='#3498db', edgecolor='white')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
sns.heatmap(data.corr(), annot=True, cmap='RdYlGn', fmt='.2f')
plt.title('Correlation Matrix')
plt.show()

cols = ['Glucose', 'BloodPressure', 'BMI']
for col in cols:
    data[col] = data[col].replace(0, data[col].mean())

X = data.drop('Outcome', axis=1)
y = data['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Data Preprocessing Completed")

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print("\nModel Accuracy:", round(accuracy * 100, 2), "%")

cm = confusion_matrix(y_test, predictions)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Diabetes', 'Diabetes'],
            yticklabels=['No Diabetes', 'Diabetes'])
plt.title('Confusion Matrix', fontsize=16)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

features = X.columns
importances = model.feature_importances_
data_plot = pd.DataFrame({'Feature': features, 'Importance': importances}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=data_plot, palette='viridis', hue='Feature', legend=False)
plt.title('Feature Importance')
plt.show()

import numpy as np
def glucosense_predict(data_input):
    data_input = np.array(data_input).reshape(1, -1)
    data_input = scaler.transform(data_input)
    probability = model.predict_proba(data_input)[0][1]

    print("\n--- GlucoSense Result ---")
    print(f"Risk Probability: {round(probability * 100, 2)}%")

    if probability > 0.7:
        print("RESULT: HIGH RISK")
    elif probability > 0.4:
        print("RESULT: MEDIUM RISK")
    else:
        print("RESULT: LOW RISK")

sample_data = [2, 140, 80, 25, 100, 32.5, 0.5, 45]
glucosense_predict(sample_data)

"""Conclusion
• Project Goal: GlucoSense successfully predicts diabetes risk using machine learning techniques.
• Best Model: The Random Forest algorithm achieved the highest accuracy and provided the most improved prediction performance.
• Impact: This system can be a valuable tool for early health monitoring and risk prevention.

Project Team Members:
• Renad Al-Talhabi
• Amal Salman
• Jumana Al-Dhafi

## 🔗 Project References
- https://github.com/Priyanshu88/Diabetes-Prediction  
- https://github.com/nicolelumagui/ML-Exercise_Pima-Indians-Diabetes_Classification  
- https://github.com/anandprakash0/Diabetes-prediction  
- https://github.com/omkarkshet/Diabetes-Prediction-Using-Machine-Learning-Techniques
"""